type Usuario {
  id : Int
  nome : String
  email : String
  nomeFile : String
  perfil : String
}

input UsuarioInput {
  nome : String
  email : String
}

type Query {
  usuario(id : Int) : Usuario
  usuarios : [Usuario]
  Usuario : String
}

type Mutation {
  cadastrarUsuario(data: UsuarioInput) : Usuario!
  atualizarUsuario(id : Int!, data :  UsuarioInput) : Usuario!
  deletarUsuario(id : Int!) : Boolean!
}
